### ISSUE TITLE
chore: Rename theme.css in custom/customDropdown and custom/customTextInput to ComponentName.scss

### ISSUE THREAD

**Issue by kanyuga** [andela/learning-map-front#54]
The stylesheet files for `common/customDropdown` and `common/customTextInput` are SCSS files named `theme.css`. These should be renamed to `CustomDropdown.scss` and `CustomTextInput.scss` for consistency with the rest of the codebase.

**Comment by BolajiOlajide** [comment]
@andela-kakpobome Can we have this as a chore?

**Comment by andela-kakpobome** [comment]
@BolajiOlajide sure, you can draft it

**Comment by andela-kakpobome** [comment]
@kanyuga we tried to rectify this but it seems one of our major dependencies, ReactToolbox requires that we have the `.css` extension, otherwise it won't recognize the file. I'm going to close this out, as for now, it can't be helped.
